story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("story10.urls"))
]

story10/urls.py
from django.urls import path
from .views import index, user_login, user_loginsuccess, user_logout, user_signup

app_name = 'story10'
urlpatterns = [
    path('', index, name='index'),
    path('login', user_login, name='login'),
    path('loginsuccess', user_loginsuccess, name='loginsuccess'),
    path('logout', user_logout, name='logout'),
    path('signup', user_signup, name='signup')
]

story10/models.py
from django.db import models

# Create your models here.

story10/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'index.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")        
        if not username or not password:
            messages.error(request, "Invalid Login, Please Try Again!")
            return render(request, 'login.html')
        user = authenticate(request,username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('story10:loginsuccess')
        messages.error(request,"Wrong Username or Password")
        return render(request,'login.html')
    else:   
        return render(request, 'login.html')

def user_signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if not username or not password:
            messages.error(request, "Please Fill out the Data Field")
            return render(request, 'signup.html')

        try:
            user = User.objects.get(username=username)
            messages.error(request, "Username is already taken by another user")
            return render(request, 'signup.html')
        except:
            user = User.objects.create_user(username=username, password=password)
            messages.success(request, "Sign Up Success")
            return redirect(reverse('story10:index'))
    else:
        return render(request,'signup.html')
@login_required(login_url='story10:index')
def user_loginsuccess(request):
    if request.method == "GET":
        return render(request, 'loginsuccess.html')

def user_logout(request):
    logout(request)
    return redirect('story10:index')

story10/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>

    <style>
        body{
            background-image: url("https://1.bp.blogspot.com/-ajd4rzU01Cs/Vl0nrj3tkMI/AAAAAAAALbA/DJ7diGU9KH0/s1600/eiffel%252Btower%252Bhd%252Bimage%252B2015-03%252B%25252810%252529.jpg");
            background-repeat: no-repeat;
            background-size: 100% 100%;
            background-attachment: fixed;
            overflow: auto;
        }
    </style>
  </head>
  <body>
    
    {% block content %}

    {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

story10/templates/index.html
{% extends "base.html" %}

{% block title %}
Story 10 PPW - Johanes Simarmata
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row pt-5 mt-5 justify-content-center">
      <div class="col-md-10">
        <h1 class="text-monospace font-weight-normal">Welcome to my Page</h1>
      </div>
      <div class="col-md-10">
        <h3 class="font-weight-light font-italic">by Johanes Simarmata</h3>
      </div>
    </div>
    <div class="row justify-content-center pt-5">
      <div class="col-md-2">
        <a href="{% url 'story10:login' %}">
          <button type="button" class="btn btn-lg btn-warning">Login</button>
        </a>
      </div>
      <div class="col-md-2">
        <a href="{% url 'story10:signup' %}">
          <button type="button" class="btn btn-lg btn-danger" name="tombol_signup_landing">Sign Up</button>      
        </a>
      </div>
    </div>
  </div>
{% endblock %}

story10/templates/login.html
{% extends "base.html" %}

{% block title %}
Login Page
{% endblock %}

{% block content %}
    {% for i in messages %}
        <script>alert("{{ i }}")</script>
    {% endfor %}
    <div class="container pt-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form action="" method="POST">
                    {% csrf_token %}
                    <label for="username">Username: </label>
                    <input type="text" name="username" id="username_box" required>
                    <br>
                    <label for="password">Password: </label>
                    <input name="password" type="password" id="password_box" required>
                    <br>
                    <input type="submit" value="Log In" class="btn btn-success" id="login-submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

story10/templates/loginsuccess.html
{% extends "base.html" %}

{% block title %}
Welcome, {{ user.username }}!
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Hello, {{ user.username }}</h1>
      <p class="lead"><a href="{% url 'story10:logout' %}"><button class="btn btn-danger">Log Out</button></a></p>
    </div>
  </div>
{% endblock %}

story10/templates/signup.html
{% extends "base.html" %}

{% block title %}
SignUp Page
{% endblock %}

{% block content %}
    {% for i in messages %}
        <script>alert("{{ i }}")</script>
    {% endfor %}
    <h1>SignUp Here</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" required>
        <label for="password">Password: </label>
        <input name="password" type="password" required>
        <input type="submit" value="Log In" class="btn btn-success" id="login-submit">
    </form>
{% endblock %}